<?php

declare(strict_types=1);

namespace lameco\kunstmaanmigrator\mapping;

use lameco\kunstmaanmigrator\legacy\EntityTableIndex;
use lameco\kunstmaanmigrator\legacy\LegacyDatabase;

/**
 * Generates a mapping skeleton from a live Kunstmaan database.
 *
 * The point is that nobody hand-writes the inventory. Every live pagepart class, page type,
 * locale, real table name, real column list and child collection is discovered and written
 * out; what a human supplies is the half a machine cannot know — which Craft block each
 * legacy part becomes.
 *
 * Every generated entry is deliberately *invalid* until someone fills it in: parts have no
 * disposition, so `validate` fails until each one is resolved. A skeleton that passed
 * validation would be a skeleton you could forget to finish.
 */
final class Skeleton
{
    /** Kunstmaan's child-collection foreign keys are conventionally `<part>_pp_id`. */
    private const CHILD_FK_SUFFIX = '_pp_id';

    /** Columns every pagepart table has; never worth listing as unmapped. */
    private const BORING_COLUMNS = ['id'];

    public function __construct(
        private readonly EntityTableIndex $entities,
    ) {
    }

    /** @param array<string, LegacyDatabase> $databases environment => connection */
    public function generate(array $databases): string
    {
        $parts = [];
        $pages = [];
        $locales = [];

        foreach ($databases as $env => $db) {
            foreach ($db->livePartPlacements() as $class => $n) {
                $parts[$class] = ($parts[$class] ?? 0) + $n;
            }

            foreach ($db->livePageTypes() as $entity => $n) {
                $pages[$entity] = ($pages[$entity] ?? 0) + $n;
            }

            $locales[$env] = $db->livePagesByLocale();
        }

        arsort($parts);
        arsort($pages);

        $probe = reset($databases);
        $childTables = $probe instanceof LegacyDatabase ? $this->childTables($probe) : [];

        $out = $this->header($parts, $pages);
        $out .= $this->environments($databases, $locales);
        $out .= $this->pagesSection($pages);
        $out .= $this->sequenceSection();
        $out .= $this->partsSection($parts, $probe, $childTables);
        $out .= $this->tailSections();

        return $out;
    }

    /** @param array<string, int> $parts @param array<string, int> $pages */
    private function header(array $parts, array $pages): string
    {
        return <<<YAML
            # Mapping skeleton — generated by `kuma-compile init`.
            #
            # Discovered from the live legacy database: {$this->count($parts)} pagepart classes
            # ({$this->sum($parts)} live placements) and {$this->count($pages)} page types
            # ({$this->sum($pages)} live pages).
            #
            # WHAT YOU FILL IN
            #   parts.*   — the Craft block each legacy pagepart becomes, and its field map.
            #   pages.*   — the section + entry type each legacy page becomes.
            #   ignore:   — every legacy column you are deliberately not migrating.
            #
            # This file does NOT validate as generated: every part lacks a disposition, so
            # `kuma-compile validate` fails until each one is resolved. That is intentional —
            # a skeleton you could forget to finish is worse than one that fails loudly.
            #
            # Run `kuma-compile validate <this file>` as you go, and `coverage` when it passes.

            version: 1


            YAML;
    }

    /**
     * @param array<string, LegacyDatabase> $databases
     * @param array<string, array<string, int>> $locales
     */
    private function environments(array $databases, array $locales): string
    {
        $out = "# ─────────────────────────────────────────────────────────────────────────────\n";
        $out .= "# Every legacy locale needs a Craft site handle, or an explicit !unmapped declaration.\n";
        $out .= "environments:\n";

        foreach ($databases as $env => $db) {
            $out .= sprintf("  %s:\n", $env);
            $out .= sprintf("    database: %s\n", $db->database);
            $out .= "    mediaRoot: ~                        # TODO: legacy media root on disk\n";
            $out .= "    locales:\n";

            foreach ($locales[$env] ?? [] as $lang => $pages) {
                $out .= sprintf(
                    "      %-10s ~                     # TODO: Craft site handle — %s live pages\n",
                    $lang . ':',
                    number_format($pages),
                );
            }

            $out .= "\n";
        }

        return $out;
    }

    /** @param array<string, int> $pages */
    private function pagesSection(array $pages): string
    {
        $out = "# ─────────────────────────────────────────────────────────────────────────────\n";
        $out .= "pages:\n";

        foreach ($pages as $entity => $live) {
            $table = $this->entities->tableFor($entity);
            $out .= sprintf("  %s:\n", $entity);
            $out .= sprintf("    live: %d\n", $live);
            $out .= sprintf("    table: %s\n", $table ?? '~                    # TODO: source table');
            $out .= "    section: ~                          # TODO\n";
            $out .= "    entryType: ~                        # TODO\n";
        }

        return $out . "\n";
    }

    private function sequenceSection(): string
    {
        return <<<'YAML'
            # ─────────────────────────────────────────────────────────────────────────────
            # Window rules over the ordered part list of a context, applied before any block is
            # emitted. Use these where one Craft block corresponds to a *run* of legacy parts —
            # most commonly an inline heading part absorbed by the block that follows it.
            #
            # sequence:
            #   - id: heading-absorb
            #     match: Header > *
            #     guard: target.hasField(heading) && target.heading == empty
            #     action: absorb
            #     map: { heading: head.title }
            #     runs: first
            #     else: heading-standalone
            sequence: []


            YAML;
    }

    /**
     * @param array<string, int> $parts
     * @param array<string, list<array{table: string, fk: string}>> $childTables
     */
    private function partsSection(array $parts, LegacyDatabase|false $probe, array $childTables): string
    {
        $out = "# ─────────────────────────────────────────────────────────────────────────────\n";
        $out .= "# Ordered by live volume: the top of this list is where the content actually is.\n";
        $out .= "parts:\n";

        foreach ($parts as $class => $live) {
            $table = $this->entities->tableFor($class);

            $out .= sprintf("  %s:\n", $class);
            $out .= sprintf("    live: %d\n", $live);
            $out .= sprintf("    table: %s\n", $table ?? '~                    # TODO: source table');
            $out .= "    block: ~                            # TODO: Craft block handle,\n";
            $out .= "                                        #  or drop:/manual:/consumedBy:\n";

            if ($table !== null && $probe instanceof LegacyDatabase && $probe->hasTable($table)) {
                $columns = array_values(array_diff($probe->columns($table), self::BORING_COLUMNS));

                if ($columns !== []) {
                    $out .= "    map: {}                             # TODO: legacy column -> Craft field\n";
                    $out .= sprintf(
                        "    ignore: [%s]  # TODO: move what you migrate into map:\n",
                        implode(', ', $columns),
                    );
                }

                // Doctrine relations are authoritative; the FK-name heuristic is the fallback.
                $children = $this->entities->childrenOf($class) ?? $childTables[$table] ?? [];

                if ($children !== []) {
                    $out .= "    children:\n";

                    // A part may own several collections (Feature has both feature_items and
                    // feature_highlight_items), so each needs its own placeholder key — a
                    // repeated `~:` would silently collapse to one entry.
                    foreach ($children as $i => $child) {
                        $childColumns = array_values(array_diff(
                            $probe->columns($child['table']),
                            [...self::BORING_COLUMNS, $child['fk'], 'weight'],
                        ));

                        $out .= sprintf(
                            "      TODO_%d:                           # TODO: target Matrix field handle for %s\n",
                            $i + 1,
                            $child['table'],
                        );
                        $out .= sprintf("        table: %s\n", $child['table']);
                        $out .= sprintf("        fk: %s\n", $child['fk']);
                        $out .= "        order: weight\n";
                        $out .= sprintf("        ignore: [%s]\n", implode(', ', $childColumns));
                    }
                }
            }
        }

        return $out . "\n";
    }

    private function tailSections(): string
    {
        return <<<'YAML'
            # ─────────────────────────────────────────────────────────────────────────────
            # Legacy form-context parts become a Formie form plus a block that references it.
            forms:
              context: form
              target: formie
              fields: {}

            # Footer / navigation contexts become globals, not entries.
            globals: {}

            # Legacy redirect pages become Retour rules.
            redirects: {}

            transforms: {}

            # Deliberate non-goals. Anything live that appears in no other lane must be declared
            # here with a reason, or `coverage` reports it as a hole and exits non-zero.
            unmapped:
              pageTypes: {}
              parts: {}
            YAML;
    }

    /**
     * Child collection tables, keyed by the parent pagepart table.
     *
     * Discovery is by the `<token>_pp_id` foreign-key convention. The token does not map
     * cleanly onto a table name: `benefit_pp_id` belongs to `..._benefits_page_parts`
     * (plural), and `google_maps_pp_id` suffix-matches both `..._google_maps_page_parts`
     * and `..._content_google_maps_page_parts`. Ambiguity resolves to the shortest
     * candidate, which is the one whose token starts at a real boundary.
     *
     * @return array<string, list<array{table: string, fk: string}>>
     */
    private function childTables(LegacyDatabase $db): array
    {
        $partTables = array_values(array_filter(
            $db->tables(),
            static fn (string $t): bool => str_ends_with($t, '_page_parts'),
        ));

        $children = [];

        foreach ($db->tables() as $table) {
            if (str_ends_with($table, '_page_parts')) {
                continue;
            }

            foreach ($db->columns($table) as $column) {
                if (!str_ends_with($column, self::CHILD_FK_SUFFIX)) {
                    continue;
                }

                $token = substr($column, 0, -strlen(self::CHILD_FK_SUFFIX));
                $parent = $this->parentTableFor($token, $partTables);

                if ($parent !== null) {
                    $children[$parent][] = ['table' => $table, 'fk' => $column];
                }
            }
        }

        return $children;
    }

    /**
     * @param list<string> $partTables
     */
    private function parentTableFor(string $token, array $partTables): ?string
    {
        $candidates = [];

        foreach ($partTables as $table) {
            foreach ([$token, $token . 's'] as $form) {
                if ($table === $form . '_page_parts' || str_ends_with($table, '_' . $form . '_page_parts')) {
                    $candidates[] = $table;

                    break;
                }
            }
        }

        if ($candidates === []) {
            return null;
        }

        usort($candidates, static fn (string $a, string $b): int => strlen($a) <=> strlen($b));

        return $candidates[0];
    }

    /** @param array<string, int> $counts */
    private function count(array $counts): string
    {
        return number_format(count($counts));
    }

    /** @param array<string, int> $counts */
    private function sum(array $counts): string
    {
        return number_format(array_sum($counts));
    }
}
